# About Dataset

The Online Retail Dataset consists of records about retail transactions conducted online.
It contains information about customer purchases, including the invoice number, stock code,
description of the items purchased, quantity, unit price, invoice date, customer ID, and country.

## Column Descriptions

| # | Column | Description |
|---|--------|-------------|
| 1 | **InvoiceNo** | A unique identifier for each transaction or invoice. |
| 2 | **StockCode** | A code representing the stock or item purchased. |
| 3 | **Description** | A textual description of the item purchased. |
| 4 | **Quantity** | The quantity of the item purchased in each transaction. |
| 5 | **InvoiceDate** | The date and time when the transaction occurred. |
| 6 | **UnitPrice** | The price per unit of the item purchased. |
| 7 | **CustomerID** | The unique identifier for the customer making the purchase. |
| 8 | **Country** | The country where the transaction took place. |

## Dataset Overview

- **Total Records:** 542,000+
- **Missing Values:** Present in `Description` and `CustomerID` columns
- **Data Types:** Integers, Floats, Datetime objects, and Strings

## Use Cases

This dataset provides valuable insights into:

- Customer purchasing behavior
- Item popularity
- Sales trends over time
- Geographic distribution of transactions

It can be used for various analytical purposes, including:

- Customer segmentation
- Sales forecasting
- Market analysis

In [1]:
import pandas as pd
import numpy as np

In [2]:
path = r"..\Data\customer.xlsx"
df = pd.read_excel(path)

In [3]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [4]:
df.shape

(541909, 8)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB

In [6]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [7]:
df.describe()

            Quantity                 InvoiceDate      UnitPrice     CustomerID
count  541909.000000                      541909  541909.000000  406829.000000
mean        9.552250  2011-07-04 13:34:57.156386       4.611114   15287.690570
min    -80995.000000         2010-12-01 08:26:00  -11062.060000   12346.000000
25%         1.000000         2011-03-28 11:34:00       1.250000   13953.000000
50%         3.000000         2011-07-19 17:17:00       2.080000   15152.000000
75%        10.000000         2011-10-19 11:27:00       4.130000   16791.000000
max     80995.000000         2011-12-09 12:50:00   38970.000000   18287.000000
std       218.081158                         NaN      96.759853    1713.600303

In [8]:
print(df.duplicated().sum())
df.drop_duplicates(inplace = True)

5268

In [9]:
# Drop Missing data

df = df.dropna()

In [10]:
# Create a column call Total Price
df['TotalPrice'] = df['Quantity'] * df['UnitPrice']

In [11]:
# Create Day, Month, Year columns
df['Year'] = df['InvoiceDate'].dt.year
df['Month'] = df['InvoiceDate'].dt.month
df['Day'] = df['InvoiceDate'].dt.day

In [12]:
saveing_path = r"..\Data\cleaned_customer.csv"
df.to_csv(saveing_path, index = False)

In [13]:
customer_country=df[['Country','CustomerID']].drop_duplicates()
customer_country.groupby(['Country'])['CustomerID'].aggregate('count').reset_index().sort_values('CustomerID', ascending=False)

                 Country  CustomerID
35        United Kingdom        3950
14               Germany          95
13                France          87
30                 Spain          31
3                Belgium          25
32           Switzerland          21
26              Portugal          19
18                 Italy          15
12               Finland          12
1                Austria          11
24                Norway          10
0              Australia           9
9                Denmark           9
23           Netherlands           9
6        Channel Islands           9
19                 Japan           8
31                Sweden           8
7                 Cyprus           8
25                Poland           6
36           Unspecified           4
33                   USA           4
5                 Canada           4
17                Israel           4
15                Greece           4
10                  EIRE           3
34  United Arab Emirates           2
2                Bahrain           2
22                 Malta           2
4                 Brazil           1
20               Lebanon           1
16               Iceland           1
8         Czech Republic           1
11    European Community           1
28          Saudi Arabia           1
27                   RSA           1
21             Lithuania           1
29             Singapore           1